tower_viewer_arn_prefix: arn:aws:sts::620117233256:assumed-role/AWSReservedSSO_TowerViewer_f2b94a34fa40b6fd
sso_admin_role:
  arn: arn:aws:iam::620117233256:role/aws-reserved/sso.amazonaws.com/AWSReservedSSO_Administrator_796a395ce7a0eea6
