template:
  path: tower-project.j2
stack_name: iatlas-project

stack_tags:
  Department: DNT
  Project: iAtlas
  OwnerEmail: thomas.yu@sagebase.org
  CostCenter: iAtlas 3 / 314900

parameters:
  S3ReadWriteAccessArns:
    - "{{stack_group_config.tower_viewer_arn_prefix}}/thomas.yu@sagebase.org"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/adam.taylor@sagebase.org"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/bryan.fauble@sagebase.org"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/rixing.xu@sagebase.org"
    # The following roles don't exist since the users are not Sage employees.
    # However, this will ensure that they are added to the Tower workspace
    # until we find a permanent solution for listing external users.
    - "{{stack_group_config.tower_viewer_arn_prefix}}/benjamin_vincent@med.unc.edu"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/dbortone@email.unc.edu"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/steven_vensko@med.unc.edu"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/cheimann@isbscience.org"
    - "{{stack_group_config.tower_viewer_arn_prefix}}/vesteinn.thorsson@isbscience.org"
  AccountAdminArns:
    - "{{stack_group_config.sso_admin_role.arn}}"
    - !stack_output_external sagebase-github-oidc-workflows-prod-nextflow-infra::ProviderRoleArn
  TemplateRootUrl: "https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com"
  TowerForgePolicyArn: !stack_output_external nextflow-forge-iam-policy::NextFlowForgePolicyArn
  TowerLaunchPolicyArn: !stack_output_external nextflow-launch-iam-policy::NextFlowLaunchPolicyArn

dependencies:
  - common/nextflow-forge-iam-policy.yaml
  - common/nextflow-launch-iam-policy.yaml
  - projects-prod/shared-ce-prod-project.yaml

sceptre_user_data:
  ManualComputeEnvs:    # use the shared project's forge batch CEs to run pipelines
    - WorkspaceName: shared-ce-prod-project
      ComputeEnvName: shared-ce-prod-project-ondemand-v14
    - WorkspaceName: shared-ce-prod-project
      ComputeEnvName: shared-ce-prod-project-spot-v14
