Description: Policy for NextFlow Forge service user to launch workflows
AWSTemplateFormatVersion: 2010-09-09
Resources:
  NextFlowLaunchPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
            - s3:Get*
            - s3:List*
            - batch:DescribeJobQueues
            - batch:CancelJob
            - batch:SubmitJob
            - batch:ListJobs
            - batch:DescribeComputeEnvironments
            - batch:TerminateJob
            - batch:DescribeJobs
            - batch:RegisterJobDefinition
            - batch:DescribeJobDefinitions
            - ecs:DescribeTasks
            - ec2:DescribeInstances
            - ec2:DescribeInstanceTypes
            - ec2:DescribeInstanceAttribute
            - ecs:DescribeContainerInstances
            - ec2:DescribeInstanceStatus
            - ec2:DescribeImages
            - logs:Describe*
            - logs:Get*
            - logs:List*
            - logs:StartQuery
            - logs:StopQuery
            - logs:TestMetricFilter
            - logs:FilterLogEvents
          Resource: "*"
Outputs:
  NextFlowLaunchPolicyArn:
    Value: !Ref NextFlowLaunchPolicy
    Export:
      Name: !Sub '${AWS::Region}-${AWS::StackName}-NextFlowLaunchPolicyArn'
