name: deploy-prod

on:
  push:
    branches: ['prod']
    paths-ignore:
      - '**.md'

jobs:
  deploy-infra:
    uses: "./.github/workflows/rw-deploy-infra.yaml"
    secrets: inherit
    with:
      job-environment: "workflows-nextflow-prod"
      sceptre-suffix: "prod"
      aws-role-to-assume: "arn:aws:iam::728882028485:role/sagebase-github-oidc-workflows-prod-nextflow-infra"
      aws-assume-role-duration: 3600
  deploy-projects:
    needs: deploy-infra
    uses: "./.github/workflows/rw-deploy-projects.yaml"
    secrets: inherit
    with:
      job-environment: "workflows-nextflow-prod"
      sceptre-suffix: "prod"
      tower-url: "https://tower.sagebionetworks.org"
      aws-role-to-assume: "arn:aws:iam::728882028485:role/sagebase-github-oidc-workflows-prod-nextflow-infra"
      aws-assume-role-duration: 3600
  validate-prod:
    needs: deploy-projects
    uses: "./.github/workflows/integration-test.yaml"
    secrets:
      nextflowtower_connection_uri: ${{ secrets.NEXTFLOWTOWER_CONNECTION_URI_PROD }}
      synapse_connection_uri: ${{ secrets.SYNAPSE_CONNECTION_URI }}
    with:
      job-environment: "workflows-nextflow-prod"
      aws-role-to-assume: "arn:aws:iam::728882028485:role/sagebase-github-oidc-workflows-prod-nextflow-infra"
      aws-assume-role-duration: 7200
      dataset_id: "syn51514585"
      s3_prefix: "s3://example-project-tower-scratch/work"
  deploy-ampad:
    needs: validate-prod
    uses: "./.github/workflows/rw-deploy-projects.yaml"
    secrets: inherit
    with:
      job-environment: "org-sagebase-strides-ampad-workflows"
      sceptre-suffix: "ampad"
      tower-url: "https://tower.sagebionetworks.org"
      aws-role-to-assume: "arn:aws:iam::751556145034:role/github-oidc-nextflow-infra"
  deploy-sagebrain:
    needs: validate-prod
    uses: "./.github/workflows/rw-deploy-projects.yaml"
    secrets: inherit
    with:
      job-environment: "org-sagebase-sagebrain-workflows"
      sceptre-suffix: "sagebrain"
      tower-url: "https://tower.sagebionetworks.org"
      aws-role-to-assume: "arn:aws:iam::620117233256:role/sagebase-github-oidc-sage-bionetworks-it-sagebrain-infra"
