name: deploy-prod

on:
  push:
    branches: ['prod']
    paths-ignore:
      - '**.md'

jobs:
  test:
    uses: ./.github/workflows/test.yaml
  deploy-prod:
    uses: "./.github/workflows/rw-deploy.yaml"
    secrets: inherit
    with:
      job-environment: "workflows-nextflow-prod"
      sceptre-suffix: "prod"
      tower-url: "https://tower.sagebionetworks.org"
      aws-role-to-assume: "arn:aws:iam::728882028485:role/sagebase-github-oidc-workflows-prod-nextflow-infra"
      aws-assume-role-duration: 7200
  deployment-validation:
    uses: "./.github/workflows/integration-test.yaml"
    secrets: inherit
    with:
      aws-role-to-assume: "arn:aws:iam::728882028485:role/sagebase-github-oidc-workflows-prod-nextflow-infra"
      aws-assume-role-duration: 7200
      dataset_id: "syn51514585"
      s3_prefix: "s3://example-project-tower-scratch/work"
  deploy-ampad:
    needs:
      - deploy-prod
      - deployment-validation
    uses: "./.github/workflows/rw-deploy.yaml"
    secrets: inherit
    with:
      job-environment: "org-sagebase-strides-ampad-workflows"
      sceptre-suffix: "ampad"
      tower-url: "https://tower.sagebionetworks.org"
      aws-role-to-assume: "arn:aws:iam::751556145034:role/github-oidc-nextflow-infra"
