name: deploy-dev

on:
  push:
    branches: ['dev']
    paths-ignore:
      - '**.md'

jobs:
  deploy-infra:
    uses: "./.github/workflows/rw-deploy-infra.yaml"
    secrets: inherit
    with:
      job-environment: "workflows-nextflow-dev"
      sceptre-suffix: "dev"
      aws-role-to-assume: "arn:aws:iam::035458030717:role/sagebase-github-oidc-workflows-dev-nextflow-infra"
      aws-assume-role-duration: 3600
  deploy-projects:
    needs: deploy-infra
    uses: "./.github/workflows/rw-deploy-projects.yaml"
    secrets: inherit
    with:
      job-environment: "workflows-nextflow-dev"
      sceptre-suffix: "dev"
      tower-url: "https://tower-dev.sagebionetworks.org"
      aws-role-to-assume: "arn:aws:iam::035458030717:role/sagebase-github-oidc-workflows-dev-nextflow-infra"
      aws-assume-role-duration: 3600
  validate-dev:
    needs: deploy-projects
    uses: "./.github/workflows/integration-test.yaml"
    secrets:
      tower-token: ${{ secrets.TOWER_TOKEN }}
    with:
      job-environment: "workflows-nextflow-dev"
      tower-url: "https://tower-dev.sagebionetworks.org"
      workspace: "Sage-Bionetworks/example-dev-project"
      compute-env: "manual-shared-ce-dev-project-spot-v13"
      work-dir: "s3://example-dev-project-tower-scratch/work"
