name: deploy-dev

on:
  push:
    branches: ['dev']
    paths-ignore:
      - '**.md'

jobs:
  deploy-dev:
    uses: "./.github/workflows/rw-deploy.yaml"
    secrets: inherit
    with:
      job-environment: "workflows-nextflow-dev"
      sceptre-suffix: "dev"
      tower-url: "https://tower-dev.sagebionetworks.org"
      aws-role-to-assume: "arn:aws:iam::035458030717:role/sagebase-github-oidc-workflows-dev-nextflow-infra"
      aws-assume-role-duration: 7200
  deployment-validation:
    needs: deploy-dev
    uses: "./.github/workflows/integration-test.yaml"
    secrets:
      nextflowtower_connection_uri: ${{ secrets.NEXTFLOWTOWER_CONNECTION_URI_DEV }}
      synapse_connection_uri: ${{ secrets.SYNAPSE_CONNECTION_URI }}
    with:
      aws-role-to-assume: "arn:aws:iam::035458030717:role/sagebase-github-oidc-workflows-dev-nextflow-infra"
      aws-assume-role-duration: 7200
      dataset_id: "syn51514585"
      s3_prefix: "s3://example-dev-project-tower-scratch/work"
