name: test

on:
  workflow_call: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up python and cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pipenv'
      - name: Install pipenv
        run: pip install -U pipenv
      - name: Install dependencies
        run: pipenv install --dev
      - name: Run pre-commit linters
        uses: pre-commit/action@v3.0.0
